title: General Wisdom Docs
email: support@mission-sciences.com
description: >-
  Official documentation for the General Wisdom platform, created by Mission Sciences.
domain: docs.generalwisdom.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://docs.generalwisdom.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  Mission-Sciences

# Build settings
theme: just-the-docs
